-- EasyABC first-party analytics setup
-- Run this once in Supabase SQL Editor.
-- Privacy: stores only anonymous browser/session IDs and event names.
-- No IP address, customer name, email, phone, or user-agent is stored.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in (
      'page_view',
      'product_view',
      'add_to_cart',
      'checkout_started',
      'payment_opened'
    )
  ),
  visitor_id text not null check (char_length(visitor_id) between 1 and 100),
  session_id text not null check (char_length(session_id) between 1 and 100),
  product_id bigint references public.products(id) on delete set null,
  order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events(created_at desc);

create index if not exists analytics_events_event_created_idx
  on public.analytics_events(event_type, created_at desc);

create index if not exists analytics_events_visitor_created_idx
  on public.analytics_events(visitor_id, created_at desc);

create index if not exists analytics_events_product_created_idx
  on public.analytics_events(product_id, created_at desc);

alter table public.analytics_events enable row level security;

grant insert on table public.analytics_events to anon, authenticated;
grant select on table public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists "analytics public insert" on public.analytics_events;
create policy "analytics public insert"
on public.analytics_events
for insert
to anon, authenticated
with check (
  event_type in (
    'page_view',
    'product_view',
    'add_to_cart',
    'checkout_started',
    'payment_opened'
  )
);

drop policy if exists "analytics admin read" on public.analytics_events;
create policy "analytics admin read"
on public.analytics_events
for select
to authenticated
using (public.is_admin());

create or replace function public.get_admin_analytics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_today_start timestamptz :=
    date_trunc('day', timezone('Asia/Kuala_Lumpur', now()))
    at time zone 'Asia/Kuala_Lumpur';
  v_month_start timestamptz :=
    date_trunc('month', timezone('Asia/Kuala_Lumpur', now()))
    at time zone 'Asia/Kuala_Lumpur';
  v_result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Not authorized';
  end if;

  select jsonb_build_object(
    'today', jsonb_build_object(
      'page_views', count(*) filter (where event_type='page_view' and created_at>=v_today_start),
      'unique_visitors', count(distinct visitor_id) filter (where created_at>=v_today_start),
      'product_views', count(*) filter (where event_type='product_view' and created_at>=v_today_start),
      'add_to_cart', count(*) filter (where event_type='add_to_cart' and created_at>=v_today_start),
      'checkout_started', count(*) filter (where event_type='checkout_started' and created_at>=v_today_start),
      'payment_opened', count(*) filter (where event_type='payment_opened' and created_at>=v_today_start),
      'paid_orders', (
        select count(*) from public.orders
        where status='paid' and paid_at>=v_today_start
      ),
      'revenue', (
        select coalesce(sum(amount),0) from public.orders
        where status='paid' and paid_at>=v_today_start
      )
    ),
    'month', jsonb_build_object(
      'page_views', count(*) filter (where event_type='page_view' and created_at>=v_month_start),
      'unique_visitors', count(distinct visitor_id) filter (where created_at>=v_month_start),
      'product_views', count(*) filter (where event_type='product_view' and created_at>=v_month_start),
      'add_to_cart', count(*) filter (where event_type='add_to_cart' and created_at>=v_month_start),
      'checkout_started', count(*) filter (where event_type='checkout_started' and created_at>=v_month_start),
      'payment_opened', count(*) filter (where event_type='payment_opened' and created_at>=v_month_start),
      'paid_orders', (
        select count(*) from public.orders
        where status='paid' and paid_at>=v_month_start
      ),
      'revenue', (
        select coalesce(sum(amount),0) from public.orders
        where status='paid' and paid_at>=v_month_start
      )
    ),
    'all_time', jsonb_build_object(
      'page_views', count(*) filter (where event_type='page_view'),
      'unique_visitors', count(distinct visitor_id),
      'product_views', count(*) filter (where event_type='product_view'),
      'add_to_cart', count(*) filter (where event_type='add_to_cart'),
      'checkout_started', count(*) filter (where event_type='checkout_started'),
      'payment_opened', count(*) filter (where event_type='payment_opened'),
      'paid_orders', (
        select count(*) from public.orders where status='paid'
      ),
      'revenue', (
        select coalesce(sum(amount),0) from public.orders where status='paid'
      )
    ),
    'top_products', coalesce((
      select jsonb_agg(to_jsonb(x))
      from (
        select
          p.id,
          p.name,
          count(*) filter (where e.event_type='product_view') as views,
          count(*) filter (where e.event_type='add_to_cart') as adds
        from public.analytics_events e
        join public.products p on p.id=e.product_id
        where e.event_type in ('product_view','add_to_cart')
        group by p.id,p.name
        order by count(*) filter (where e.event_type='product_view') desc,
                 count(*) filter (where e.event_type='add_to_cart') desc,
                 p.name
        limit 10
      ) x
    ), '[]'::jsonb)
  )
  into v_result
  from public.analytics_events;

  return v_result;
end;
$$;

revoke all on function public.get_admin_analytics() from public;
grant execute on function public.get_admin_analytics() to authenticated;
