-- EasyABC announcement / notification setup
-- Run once in Supabase SQL Editor.

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null default 'EasyABC Update',
  message text not null,
  button_text text,
  button_url text,
  active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.announcements enable row level security;

grant select on table public.announcements to anon, authenticated;
grant insert, update, delete on table public.announcements to authenticated;
grant usage, select on sequence public.announcements_id_seq to authenticated;

drop policy if exists "announcements public read active" on public.announcements;
create policy "announcements public read active"
on public.announcements
for select
to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "announcements admin insert" on public.announcements;
create policy "announcements admin insert"
on public.announcements
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "announcements admin update" on public.announcements;
create policy "announcements admin update"
on public.announcements
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "announcements admin delete" on public.announcements;
create policy "announcements admin delete"
on public.announcements
for delete
to authenticated
using (public.is_admin());

-- Only one active announcement is intended at a time.
create unique index if not exists announcements_one_active_idx
on public.announcements ((active))
where active = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists announcements_set_updated_at on public.announcements;
create trigger announcements_set_updated_at
before update on public.announcements
for each row
execute function public.set_updated_at();
