-- EasyABC dynamic product categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products
add column if not exists category_id bigint
references public.categories(id)
on delete set null;

create index if not exists idx_products_category_id
on public.products(category_id);

alter table public.categories enable row level security;

drop policy if exists "public read active categories"
on public.categories;

create policy "public read active categories"
on public.categories
for select
to anon, authenticated
using (active = true);

grant select on table public.categories to anon, authenticated;
grant select on table public.categories to service_role;

insert into public.categories (name, slug, description, sort_order, active)
values ('Trading', 'trading', 'Trading, market analysis and investment tools.', 1, true)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  active = true;

update public.products
set category_id = (
  select id
  from public.categories
  where slug = 'trading'
)
where id = 1;

do $$
begin
  alter publication supabase_realtime add table public.categories;
exception
  when duplicate_object then null;
end $$;
