-- EasyABC Community / Feedback Board
-- Run this file once in Supabase SQL Editor after supabase/admin_setup.sql.
-- Visitors only type a nickname + message on the storefront.
-- Your admin account can reply, hide/show, or delete posts from admin.html.

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  nickname varchar(40) not null check (char_length(trim(nickname)) between 2 and 40),
  kind text not null default 'question' check (kind in ('question','feedback','comment')),
  message text not null check (char_length(trim(message)) between 3 and 1000),
  author_id uuid references auth.users(id) on delete set null,
  admin_reply text check (admin_reply is null or char_length(admin_reply) <= 2000),
  replied_at timestamptz,
  visible boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists community_posts_created_at_idx
  on public.community_posts (created_at desc);

create index if not exists community_posts_visible_created_at_idx
  on public.community_posts (visible, created_at desc);

alter table public.community_posts enable row level security;

drop policy if exists "public read visible community posts" on public.community_posts;
create policy "public read visible community posts"
on public.community_posts
for select
to anon, authenticated
using (visible = true);

drop policy if exists "customers create community posts" on public.community_posts;
create policy "customers create community posts"
on public.community_posts
for insert
to authenticated
with check (
  author_id = auth.uid()
  and visible = true
  and admin_reply is null
  and replied_at is null
);

drop policy if exists "admins read all community posts" on public.community_posts;
create policy "admins read all community posts"
on public.community_posts
for select
to authenticated
using (public.is_admin());

drop policy if exists "admins update community posts" on public.community_posts;
create policy "admins update community posts"
on public.community_posts
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins delete community posts" on public.community_posts;
create policy "admins delete community posts"
on public.community_posts
for delete
to authenticated
using (public.is_admin());

grant select on public.community_posts to anon, authenticated;
grant insert on public.community_posts to authenticated;
grant update, delete on public.community_posts to authenticated;
grant usage, select on sequence public.community_posts_id_seq to authenticated;

-- Enable Realtime for new posts and admin replies. Safe to run more than once.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'community_posts'
  ) then
    alter publication supabase_realtime add table public.community_posts;
  end if;
end $$;
