-- EasyABC multiple product images + video gallery
-- Run once in Supabase SQL Editor.

create table if not exists public.product_media (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  media_type text not null check (media_type in ('image','video')),
  storage_path text not null,
  caption text,
  sort_order integer not null default 1,
  is_cover boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_product_media_product_id
on public.product_media(product_id);

create index if not exists idx_product_media_product_sort
on public.product_media(product_id, sort_order, id);

-- Only one cover row per product.
create unique index if not exists uq_product_media_one_cover
on public.product_media(product_id)
where is_cover = true;

alter table public.product_media enable row level security;

-- Store visitors can view gallery media records.
drop policy if exists "public read product media records"
on public.product_media;

create policy "public read product media records"
on public.product_media
for select
to anon, authenticated
using (true);

grant select
on public.product_media
to anon, authenticated;

-- Only whitelisted EasyABC admins can create/change/delete gallery records.
drop policy if exists "admins manage product media records"
on public.product_media;

create policy "admins manage product media records"
on public.product_media
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant insert, update, delete
on public.product_media
to authenticated;

grant usage, select
on sequence public.product_media_id_seq
to authenticated;

-- Keep product-media bucket public for storefront images/videos.
insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id)
do update set public = true;

-- Admin upload/delete access to files.
drop policy if exists "admins manage product media"
on storage.objects;

create policy "admins manage product media"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'product-media'
  and public.is_admin()
)
with check (
  bucket_id = 'product-media'
  and public.is_admin()
);

-- Public storefront read access.
drop policy if exists "public read product media"
on storage.objects;

create policy "public read product media"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'product-media');

-- Migrate each existing single product image into the new gallery,
-- but only when that exact image has not already been migrated.
insert into public.product_media (
  product_id,
  media_type,
  storage_path,
  sort_order,
  is_cover
)
select
  p.id,
  'image',
  p.image_path,
  1,
  true
from public.products p
where p.image_path is not null
  and btrim(p.image_path) <> ''
  and not exists (
    select 1
    from public.product_media pm
    where pm.product_id = p.id
      and pm.storage_path = p.image_path
  );

-- Realtime refresh for storefront/admin gallery changes.
do $$
begin
  alter publication supabase_realtime add table public.product_media;
exception
  when duplicate_object then null;
end $$;
