create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  emoji text not null default '📦',
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  order_no text unique not null,
  amount numeric(12,2) not null,
  status text not null default 'pending' check (status in ('pending','paid','failed','cancelled')),
  customer_name text,
  customer_phone text,
  note text,
  provider_ref text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

grant usage on schema public to anon, authenticated;
grant select on table public.products to anon, authenticated;
grant select on table public.orders to authenticated;

drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products for select to anon,authenticated using(active=true);

drop policy if exists "users read own orders" on public.orders;
create policy "users read own orders" on public.orders for select to authenticated using(auth.uid()=user_id);

do $$ begin alter publication supabase_realtime add table public.products; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.orders; exception when duplicate_object then null; end $$;

insert into public.products(name,description,price,emoji,sort_order)
select * from (values
('Retro Bluetooth Speaker','Portable retro speaker with stylish look and rich sound.',39.90,'🔊',1),
('Smart Watch Pro','Track calls, notifications and daily activity.',89.00,'⌚',2),
('Wireless Earbuds','Compact earbuds with simple Bluetooth pairing.',55.00,'🎧',3),
('Mini Desk Fan','Cooling airflow for desk, bedside and small spaces.',25.00,'🌀',4),
('Night Lamp','Soft ambient lighting with a clean modern look.',32.00,'💡',5),
('Power Bank','Reliable backup power for your phone and travel.',65.00,'🔋',6)
) v(name,description,price,emoji,sort_order)
where not exists(select 1 from public.products);
